## Part 1: Preparation
The most important thing in this ipynb is to mark the attack in the Flow data

### 1. Preprocessing

#### 1.1 Import Libraries

In [ ]:
!pwd

/content

In [ ]:
import pandas as pd
import io
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

#### 1.2 Load Flow Dataset

In [ ]:
df_flow0 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/00166cab6b88_flowstats.csv')
df_flow1 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/0017882b9a25_flowstats.csv')
df_flow2 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/44650d56ccd3_flowstats.csv')
df_flow3 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/50c7bf005639_flowstats.csv')
df_flow4 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/70ee50183443_flowstats.csv')
df_flow5 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/74c63b29d71d_flowstats.csv')
df_flow6 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/d073d5018308_flowstats.csv')
df_flow7 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/ec1a5979f489_flowstats.csv')
df_flow8 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/ec1a59832811_flowstats.csv')
df_flow9 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/flow/f4f5d88f0a3c_flowstats.csv')
df_flow2

           Timestamp  ...   NoOfFlows
0      1537760161699  ...          77
1      1537760221755  ...          77
2      1537760281805  ...          77
3      1537760341861  ...          77
4      1537760401909  ...          77
...              ...  ...         ...
43723  1540582549573  ...          66
43724  1540582609614  ...          66
43725  1540582669696  ...          66
43726  1540582729740  ...          66
43727  1540582789826  ...          66

[43728 rows x 52 columns]

#### 1.3 Load annotation data

In [ ]:
df_attack0 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/00166cab6b88.csv')
df_attack1 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/0017882b9a25.csv')
df_attack2 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/44650d56ccd3.csv')
df_attack3 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/50c7bf005639.csv')
df_attack4 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/70ee50183443.csv')
df_attack5 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/74c63b29d71d.csv')
df_attack6 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/d073d5018308.csv')
df_attack7 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/ec1a5979f489.csv')
df_attack8 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/ec1a59832811.csv')
df_attack9 = pd.read_csv('gdrive/MyDrive/Thesis-NikkiZhang/Dataset/annotation/f4f5d88f0a3c.csv')
df_attack2

   Start Time  ...           Attack
0  1540218159  ...   ArpSpoof100L2D
1  1540214943  ...     ArpSpoof1L2D
2  1540216550  ...    ArpSpoof10L2D
3  1540240592  ...    UdpDevice1L2D
4  1540249401  ...   UdpDevice10L2D
5  1540251009  ...  UdpDevice100L2D
6  1540305374  ...    UdpDevice1W2D
7  1540305984  ...   UdpDevice10W2D
8  1540306594  ...  UdpDevice100W2D

[9 rows x 4 columns]

#### 1.4 Mark the new dataset with Attack Types

In [ ]:
def mark_type_function(df_flow,df_attack):
    df_flow['Attack'] = 0
    df_flow['AttackType'] = 100
    for i in range(len(df_flow)):
        k=0
        for j in range(len(df_attack)):
            if(df_flow['Timestamp'][i]>=df_attack['Start Time'][j]*1000 and df_attack['End Time'][j]*1000>=df_flow['Timestamp'][i]):
                df_flow['Attack'][i] = 1
                if df_attack['Attack'][j] == "ArpSpoof100L2D":
                    df_flow['AttackType'][i] = 0
                elif df_attack['Attack'][j] == "ArpSpoof1L2D":
                    df_flow['AttackType'][i] = 1
                elif df_attack['Attack'][j] == "ArpSpoof10L2D":
                    df_flow['AttackType'][i] = 2
                elif df_attack['Attack'][j] == "TcpSynDevice1L2D":
                    df_flow['AttackType'][i] = 3
                elif df_attack['Attack'][j] == "TcpSynDevice10L2D":
                    df_flow['AttackType'][i] = 4
                elif df_attack['Attack'][j] == "TcpSynDevice100L2D":
                    df_flow['AttackType'][i] = 5
                elif df_attack['Attack'][j] == "PingOfDeath1L2D":
                    df_flow['AttackType'][i] = 6
                elif df_attack['Attack'][j] == "PingOfDeath10L2D":
                    df_flow['AttackType'][i] = 7
                elif df_attack['Attack'][j] == "PingOfDeath100L2D":
                    df_flow['AttackType'][i] = 8
                elif df_attack['Attack'][j] == "UdpDevice1L2D":
                    df_flow['AttackType'][i] = 9
                elif df_attack['Attack'][j] == "UdpDevice10L2D":
                    df_flow['AttackType'][i] = 10
                elif df_attack['Attack'][j] == "UdpDevice100L2D":
                    df_flow['AttackType'][i] = 11
                elif df_attack['Attack'][j] == "TcpSynReflection100L2D2L":
                    df_flow['AttackType'][i] = 12
                elif df_attack['Attack'][j] == "TcpSynReflection1L2D2L":
                    df_flow['AttackType'][i] = 13
                elif df_attack['Attack'][j] == "TcpSynReflection10L2D2L":
                    df_flow['AttackType'][i] = 14
                elif df_attack['Attack'][j] == "Smurf1L2D2L":
                    df_flow['AttackType'][i] = 15
                elif df_attack['Attack'][j] == "Smurf10L2D2L":
                    df_flow['AttackType'][i] = 16
                elif df_attack['Attack'][j] == "Smurf100L2D2L":
                    df_flow['AttackType'][i] = 17
                elif df_attack['Attack'][j] == "Snmp1L2D2L":
                    df_flow['AttackType'][i] = 18
                elif df_attack['Attack'][j] == "Snmp10L2D2L":
                    df_flow['AttackType'][i] = 19
                elif df_attack['Attack'][j] == "Snmp100L2D2L":
                    df_flow['AttackType'][i] = 20
                elif df_attack['Attack'][j] == "Snmp1L2D2W":
                    df_flow['AttackType'][i] = 21
                elif df_attack['Attack'][j] == "Snmp10L2D2W":
                    df_flow['AttackType'][i] = 22
                elif df_attack['Attack'][j] == "Snmp100L2D2W":
                    df_flow['AttackType'][i] = 23
                elif df_attack['Attack'][j] == "TcpSynReflection100W2D2W":
                    df_flow['AttackType'][i] = 24
                elif df_attack['Attack'][j] == "TcpSynReflection1W2D2W":
                    df_flow['AttackType'][i] = 25
                elif df_attack['Attack'][j] == "TcpSynReflection10W2D2W":
                    df_flow['AttackType'][i] = 26
                elif df_attack['Attack'][j] == "Snmp1W2D2W":
                    df_flow['AttackType'][i] = 27
                elif df_attack['Attack'][j] == "Snmp10W2D2W":
                    df_flow['AttackType'][i] = 28
                elif df_attack['Attack'][j] == "Snmp100W2D2W":
                    df_flow['AttackType'][i] = 29
                elif df_attack['Attack'][j] == "TcpSynDevice1W2D":
                    df_flow['AttackType'][i] = 30
                elif df_attack['Attack'][j] == "TcpSynDevice10W2D":
                    df_flow['AttackType'][i] = 31
                elif df_attack['Attack'][j] == "TcpSynDevice100W2D":
                    df_flow['AttackType'][i] = 32
                elif df_attack['Attack'][j] == "UdpDevice1W2D":
                    df_flow['AttackType'][i] = 33
                elif df_attack['Attack'][j] == "UdpDevice10W2D":
                    df_flow['AttackType'][i] = 34
                elif df_attack['Attack'][j] == "UdpDevice100W2D":
                    df_flow['AttackType'][i] = 35
                elif df_attack['Attack'][j] == "TcpSynDevice1W2D":
                    df_flow['AttackType'][i] = 36
                elif df_attack['Attack'][j] == "TcpSynDevice10W2D":
                    df_flow['AttackType'][i] = 37
                elif df_attack['Attack'][j] == "TcpSynDevice100W2D":
                    df_flow['AttackType'][i] = 38
                elif df_attack['Attack'][j] == "TcpSynReflection100W2D2W":
                    df_flow['AttackType'][i] = 39
                elif df_attack['Attack'][j] == "TcpSynReflection1W2D2W":
                    df_flow['AttackType'][i] = 40
                elif df_attack['Attack'][j] == "TcpSynReflection10W2D2W":
                    df_flow['AttackType'][i] = 41

mark_type_function(df_flow0,df_attack0)
mark_type_function(df_flow1,df_attack1)
mark_type_function(df_flow2,df_attack2)
mark_type_function(df_flow3,df_attack3)
mark_type_function(df_flow4,df_attack4)
mark_type_function(df_flow5,df_attack5)
mark_type_function(df_flow6,df_attack6)
mark_type_function(df_flow7,df_attack7)
mark_type_function(df_flow8,df_attack8)
mark_type_function(df_flow9,df_attack9)

In [ ]:
df_flow0_new = df_flow0.loc[df_flow0['Attack'] == 1]
df_flow1_new = df_flow1.loc[df_flow1['Attack'] == 1]
df_flow2_new = df_flow2.loc[df_flow2['Attack'] == 1]
df_flow3_new = df_flow3.loc[df_flow3['Attack'] == 1]
df_flow4_new = df_flow4.loc[df_flow4['Attack'] == 1]
df_flow5_new = df_flow5.loc[df_flow5['Attack'] == 1]
df_flow6_new = df_flow6.loc[df_flow6['Attack'] == 1]
df_flow7_new = df_flow7.loc[df_flow7['Attack'] == 1]
df_flow8_new = df_flow8.loc[df_flow8['Attack'] == 1]
df_flow9_new = df_flow9.loc[df_flow9['Attack'] == 1]
df_flow9_new

           Timestamp  ...  AttackType
37793  1540219776477  ...           1
37794  1540219836528  ...           1
37795  1540219896578  ...           1
37796  1540219956636  ...           1
37797  1540220016687  ...           1
...              ...  ...         ...
41780  1540463181164  ...          24
41781  1540463241214  ...          24
41782  1540463301261  ...          24
41783  1540463361308  ...          24
41784  1540463421357  ...          24

[252 rows x 82 columns]

#### 1.5 Merge all the flow data into one

In [ ]:
df = pd.concat([df_flow0_new, df_flow1_new, df_flow2_new, df_flow3_new, df_flow4_new, df_flow5_new, df_flow6_new, df_flow7_new, df_flow8_new, df_flow9_new])
df

           Timestamp  ...  ToInternetTcpPort5228Byte
4414   1527835359066  ...                        NaN
4415   1527835419103  ...                        NaN
4416   1527835479140  ...                        NaN
4417   1527835539176  ...                        NaN
4418   1527835599213  ...                        NaN
...              ...  ...                        ...
41780  1540463181164  ...                      232.0
41781  1540463241214  ...                       66.0
41782  1540463301261  ...                      232.0
41783  1540463361308  ...                       66.0
41784  1540463421357  ...                      232.0

[2300 rows x 256 columns]

#### 1.6 change the timestamp to datetime

In [ ]:
#df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='ms')
#df

#### 1.7 Order by the datetime

In [ ]:
df=df.sort_values('Timestamp')
df

           Timestamp  ...  ToInternetTcpPort5228Byte
4254   1527825687860  ...                        NaN
4255   1527825747991  ...                        NaN
4256   1527825808060  ...                        NaN
4257   1527825868143  ...                        NaN
4258   1527825928217  ...                        NaN
...              ...  ...                        ...
41780  1540463181164  ...                      232.0
41781  1540463241214  ...                       66.0
41782  1540463301261  ...                      232.0
41783  1540463361308  ...                       66.0
41784  1540463421357  ...                      232.0

[2300 rows x 256 columns]

In [ ]:
y = df['AttackType']
df = df.drop(columns="AttackType")
df = df.drop(columns="Attack")

#### 1.8 Remove unnecessary attributes

In [ ]:
df = df.drop(columns=" NoOfFlows")
list(df.columns)

['Timestamp',
 'FromInternetTcpPort40000Packet',
 'FromInternetTcpPort40000Byte',
 'FromInternetUdpPortAllPacket',
 'FromInternetUdpPortAllByte',
 'ToInternetTcpPort40000Packet',
 'ToInternetTcpPort40000Byte',
 'ToInternetUdpPortAllPacket',
 'ToInternetUdpPortAllByte',
 'FromLocalTcpPort59486Packet',
 'FromLocalTcpPort59486Byte',
 'FromLocalTcpPort554Packet',
 'FromLocalTcpPort554Byte',
 'FromLocalIcmpPortAllPacket',
 'FromLocalIcmpPortAllByte',
 'FromLocalUdpPort53IP192.168.1.1Packet',
 'FromLocalUdpPort53IP192.168.1.1Byte',
 'FromLocalTcpPort47893Packet',
 'FromLocalTcpPort47893Byte',
 'FromLocalTcpPort41086Packet',
 'FromLocalTcpPort41086Byte',
 'FromLocalTcpPort54836Packet',
 'FromLocalTcpPort54836Byte',
 'FromLocalTcpPort51125Packet',
 'FromLocalTcpPort51125Byte',
 'FromLocalTcpPort53074Packet',
 'FromLocalTcpPort53074Byte',
 'FromLocalTcpPort56035Packet',
 'FromLocalTcpPort56035Byte',
 'FromLocalUdpPort1900Packet',
 'FromLocalUdpPort1900Byte',
 'FromLocalUdpPort67IP192.168.1.1Packet',
 'FromLocalUdpPort67IP192.168.1.1Byte',
 'FromLocalTcpPort44416Packet',
 'FromLocalTcpPort44416Byte',
 'FromLocalTcpPort49152Packet',
 'FromLocalTcpPort49152Byte',
 'FromLocalTcpPort80Packet',
 'FromLocalTcpPort80Byte',
 'FromLocalArpPortAllPacket',
 'FromLocalArpPortAllByte',
 'ToLocal2PortAllIP224.0.0.251/32Packet',
 'ToLocal2PortAllIP224.0.0.251/32Byte',
 'ToLocal2PortAllIP224.0.0.22/32Packet',
 'ToLocal2PortAllIP224.0.0.22/32Byte',
 'ToLocalTcpPort47893Packet',
 'ToLocalTcpPort47893Byte',
 'ToLocalUdpPort1900IP239.255.255.250/32Packet',
 'ToLocalUdpPort1900IP239.255.255.250/32Byte',
 'ToLocalUdpPort67IP255.255.255.255/32Packet',
 'ToLocalUdpPort67IP255.255.255.255/32Byte',
 'ToLocalTcpPort54836Packet',
 'ToLocalTcpPort54836Byte',
 'ToLocalUdpPort7711IP255.255.255.255/32Packet',
 'ToLocalUdpPort7711IP255.255.255.255/32Byte',
 'ToLocalTcpPort53074Packet',
 'ToLocalTcpPort53074Byte',
 'ToLocalUdpPort1900Packet',
 'ToLocalUdpPort1900Byte',
 'ToLocalTcpPort51125Packet',
 'ToLocalTcpPort51125Byte',
 'ToLocalTcpPort41086Packet',
 'ToLocalTcpPort41086Byte',
 'ToLocal2PortAllIP239.255.255.250/32Packet',
 'ToLocal2PortAllIP239.255.255.250/32Byte',
 'ToLocalTcpPort59486Packet',
 'ToLocalTcpPort59486Byte',
 'ToLocalUdpPort53IP192.168.1.1Packet',
 'ToLocalUdpPort53IP192.168.1.1Byte',
 'ToLocalTcpPort49152Packet',
 'ToLocalTcpPort49152Byte',
 'ToLocalTcpPort443Packet',
 'ToLocalTcpPort443Byte',
 'ToLocalUdpPort67IP192.168.1.1Packet',
 'ToLocalUdpPort67IP192.168.1.1Byte',
 'ToLocalTcpPort444Packet',
 'ToLocalTcpPort444Byte',
 'ToLocalTcpPort554Packet',
 'ToLocalTcpPort554Byte',
 'ToLocalTcpPort56035Packet',
 'ToLocalTcpPort56035Byte',
 'ToLocalUdpPort5353IP224.0.0.251/32Packet',
 'ToLocalUdpPort5353IP224.0.0.251/32Byte',
 'ToLocalTcpPort44416Packet',
 'ToLocalTcpPort44416Byte',
 'ToLocal2PortAllIP224.0.0.2/32Packet',
 'ToLocal2PortAllIP224.0.0.2/32Byte',
 'ToLocalTcpPort80Packet',
 'ToLocalTcpPort80Byte',
 'ToLocalUdpPort1900IPff00::/8Packet',
 'ToLocalUdpPort1900IPff00::/8Byte',
 'ToLocalUdpPort5353IPff00::/8Packet',
 'ToLocalUdpPort5353IPff00::/8Byte',
 'ToLocal0PortAllIPff05:0:0:0:0:0:0:cPacket',
 'ToLocal0PortAllIPff05:0:0:0:0:0:0:cByte',
 'ToLocal0PortAllIPff00::/8Packet',
 'ToLocal0PortAllIPff00::/8Byte',
 'ToLocal0x0006PortAllPacket',
 'ToLocal0x0006PortAllByte',
 'ToLocal0x888ePortAllPacket',
 'ToLocal0x888ePortAllByte',
 'ToLocalArpPortAllPacket',
 'ToLocalArpPortAllByte',
 'FromInternetUdpPort123Packet',
 'FromInternetUdpPort123Byte',
 'FromInternetTcpPort443Packet',
 'FromInternetTcpPort443Byte',
 'FromInternetTcpPort80Packet',
 'FromInternetTcpPort80Byte',
 'FromInternetTcpPort465Packet',
 'FromInternetTcpPort465Byte',
 'FromInternetTcpPort5222Packet',
 'FromInternetTcpPort5222Byte',
 'ToInternetUdpPort123Packet',
 'ToInternetUdpPort123Byte',
 'ToInternetTcpPort5222Packet',
 'ToInternetTcpPort5222Byte',
 'ToInternetTcpPort80Packet',
 'ToInternetTcpPort80Byte',
 'ToInternetTcpPort443Packet',
 'ToInternetTcpPort443Byte',
 'ToInternetTcpPort465Packet',
 'ToInternetTcpPort465Byte',
 'FromInternetUdpPort53IP208.67.220.220/32Packet',
 'FromInternetUdpPort53IP208.67.220.220/32Byte',
 'ToInternetUdpPort53IP208.67.220.220/32Packet',
 'ToInternetUdpPort53IP208.67.220.220/32Byte',
 'FromLocalIcmpPortAllIP192.168.1.1Packet',
 'FromLocalIcmpPortAllIP192.168.1.1Byte',
 'FromLocalUdpPort50000Packet',
 'FromLocalUdpPort50000Byte',
 'ToLocalIcmpPortAllIP192.168.1.1Packet',
 'ToLocalIcmpPortAllIP192.168.1.1Byte',
 'FromInternetUdpPort33434Packet',
 'FromInternetUdpPort33434Byte',
 'ToInternetUdpPort33434Packet',
 'ToInternetUdpPort33434Byte',
 'FromLocalTcpPort9999Packet',
 'FromLocalTcpPort9999Byte',
 'ToLocalTcpPort9999Packet',
 'ToLocalTcpPort9999Byte',
 'FromInternetTcpPort50443Packet',
 'FromInternetTcpPort50443Byte',
 'ToInternetTcpPort50443Packet',
 'ToInternetTcpPort50443Byte',
 'ToLocal58PortAllIPff00::/8Packet',
 'ToLocal58PortAllIPff00::/8Byte',
 'FromInternetIcmpPortAllPacket',
 'FromInternetIcmpPortAllByte',
 'FromInternetUdpPort500Packet',
 'FromInternetUdpPort500Byte',
 'FromInternetUdpPort4500Packet',
 'FromInternetUdpPort4500Byte',
 'ToInternetIcmpPortAllPacket',
 'ToInternetIcmpPortAllByte',
 'ToInternetUdpPort4500Packet',
 'ToInternetUdpPort4500Byte',
 'ToInternetUdpPort500Packet',
 'ToInternetUdpPort500Byte',
 'FromInternetUdpPort53IP8.8.8.8/32Packet',
 'FromInternetUdpPort53IP8.8.8.8/32Byte',
 'ToInternetUdpPort53IP8.8.8.8/32Packet',
 'ToInternetUdpPort53IP8.8.8.8/32Byte',
 'FromLocalUdpPort56700Packet',
 'FromLocalUdpPort56700Byte',
 'ToLocalUdpPort56700Packet',
 'ToLocalUdpPort56700Byte',
 'ToLocalUdpPort56700Packet.1',
 'ToLocalUdpPort56700Byte.1',
 'FromInternetTcpPort56700Packet',
 'FromInternetTcpPort56700Byte',
 'ToInternetTcpPort56700Packet',
 'ToInternetTcpPort56700Byte',
 'FromInternetUdpPort123IP130.149.17.8/32Packet',
 'FromInternetUdpPort123IP130.149.17.8/32Byte',
 'FromInternetUdpPort123IP129.132.2.21/32Packet',
 'FromInternetUdpPort123IP129.132.2.21/32Byte',
 'FromInternetIcmpPortAllIP4.2.2.2/32Packet',
 'FromInternetIcmpPortAllIP4.2.2.2/32Byte',
 'FromInternetUdpPort123IP132.163.4.102/32Packet',
 'FromInternetUdpPort123IP132.163.4.102/32Byte',
 'FromInternetTcpPort3478Packet',
 'FromInternetTcpPort3478Byte',
 'ToInternetTcpPort3478Packet',
 'ToInternetTcpPort3478Byte',
 'ToInternetUdpPort123IP129.132.2.21/32Packet',
 'ToInternetUdpPort123IP129.132.2.21/32Byte',
 'ToInternetIcmpPortAllIP4.2.2.2/32Packet',
 'ToInternetIcmpPortAllIP4.2.2.2/32Byte',
 'ToInternetUdpPort123IP130.149.17.8/32Packet',
 'ToInternetUdpPort123IP130.149.17.8/32Byte',
 'ToInternetUdpPort123IP132.163.4.102/32Packet',
 'ToInternetUdpPort123IP132.163.4.102/32Byte',
 'FromLocalTcpPort49153Packet',
 'FromLocalTcpPort49153Byte',
 'FromLocalTcpPort49154Packet',
 'FromLocalTcpPort49154Byte',
 'FromLocalTcpPort8059Packet',
 'FromLocalTcpPort8059Byte',
 'ToLocalTcpPort8059Packet',
 'ToLocalTcpPort8059Byte',
 'ToLocalTcpPort49154Packet',
 'ToLocalTcpPort49154Byte',
 'ToLocalTcpPort49153Packet',
 'ToLocalTcpPort49153Byte',
 'FromInternetTcpPort8899Packet',
 'FromInternetTcpPort8899Byte',
 'FromInternetTcpPort3475Packet',
 'FromInternetTcpPort3475Byte',
 'FromInternetTcpPort8443Packet',
 'FromInternetTcpPort8443Byte',
 'ToInternetTcpPort8443Packet',
 'ToInternetTcpPort8443Byte',
 'ToInternetTcpPort8899Packet',
 'ToInternetTcpPort8899Byte',
 'ToInternetTcpPort3475Packet',
 'ToInternetTcpPort3475Byte',
 'FromLocalUdpPort3306Packet',
 'FromLocalUdpPort3306Byte',
 'FromLocalUdpPort3079Packet',
 'FromLocalUdpPort3079Byte',
 'FromLocalUdpPort3080Packet',
 'FromLocalUdpPort3080Byte',
 'FromLocalUdpPort3087Packet',
 'FromLocalUdpPort3087Byte',
 'ToLocalUdpPort3080Packet',
 'ToLocalUdpPort3080Byte',
 'ToLocalUdpPort3079Packet',
 'ToLocalUdpPort3079Byte',
 'ToLocalUdpPort3306Packet',
 'ToLocalUdpPort3306Byte',
 'ToLocalUdpPort3087Packet',
 'ToLocalUdpPort3087Byte',
 'FromInternetIcmpPortAllIP8.8.8.8/32Packet',
 'FromInternetIcmpPortAllIP8.8.8.8/32Byte',
 'ToInternetIcmpPortAllIP8.8.8.8/32Packet',
 'ToInternetIcmpPortAllIP8.8.8.8/32Byte',
 'FromLocalTcpPort8008Packet',
 'FromLocalTcpPort8008Byte',
 'FromLocalTcpPort8009Packet',
 'FromLocalTcpPort8009Byte',
 'ToLocalTcpPort8009Packet',
 'ToLocalTcpPort8009Byte',
 'ToLocalTcpPort8008Packet',
 'ToLocalTcpPort8008Byte',
 'FromInternetUdpPort443Packet',
 'FromInternetUdpPort443Byte',
 'FromInternetTcpPort5228Packet',
 'FromInternetTcpPort5228Byte',
 'ToInternetUdpPort443Packet',
 'ToInternetUdpPort443Byte',
 'ToInternetTcpPort5228Packet',
 'ToInternetTcpPort5228Byte']

#### 1.9 Visualizing missing values

In [ ]:
#sns.heatmap(df.isnull(), cbar=False)

#### 2.1 Convert NaN to 0

In [ ]:
import numpy as np
df=df.replace(np.nan, 0.0)

#### 2 Split the dataset to train and test set

In [ ]:
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

In [ ]:
# create training and testing vars
x_train, X_test, y_train, Y_test = train_test_split(df, y, test_size=0.2)
print(X_test.shape, Y_test.shape)

(460, 253) (460,)

In [ ]:
print(x_train.shape, y_train.shape)

(1840, 253) (1840,)

### Build Model

In [ ]:
import time
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix, mean_squared_error

#### 2.Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
start_time_LR=time.time()

logreg = LogisticRegression()
logreg.fit(x_train, y_train)

y_pred_LR = logreg.predict(X_test)
print("Logistic Regression Accuracy:",metrics.accuracy_score(Y_test, y_pred_LR))

Logistic Regression Accuracy: 0.09565217391304348

In [ ]:
print(confusion_matrix(Y_test, y_pred_LR))
print(classification_report(Y_test,y_pred_LR))

[[ 0  0  0 ...  0  0 17]
 [ 0  0  0 ...  0  0 26]
 [ 0  0  0 ...  0  0 24]
 ...
 [ 0  0  0 ...  0  0  5]
 [ 0  0  0 ...  0  0  5]
 [ 0  0  0 ...  0  0 44]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        17
           1       0.00      0.00      0.00        26
           2       0.00      0.00      0.00        24
           3       0.00      0.00      0.00        10
           4       0.00      0.00      0.00        11
           5       0.00      0.00      0.00        14
           6       0.00      0.00      0.00        18
           7       0.00      0.00      0.00        16
           8       0.00      0.00      0.00        11
           9       0.00      0.00      0.00         4
          10       0.00      0.00      0.00         3
          11       0.00      0.00      0.00         8
          12       0.00      0.00      0.00        12
          13       0.00      0.00      0.00         9
          14       0.00      0.00      0.00        16
          15       0.00      0.00      0.00        11
          16       0.00      0.00      0.00        12
          17       0.00      0.00      0.00         6
          18       0.00      0.00      0.00         2
          19       0.00      0.00      0.00         4
          20       0.00      0.00      0.00         2
          21       0.00      0.00      0.00         2
          22       0.00      0.00      0.00         1
          23       0.00      0.00      0.00         4
          24       0.00      0.00      0.00        20
          25       0.00      0.00      0.00        30
          26       0.00      0.00      0.00        29
          27       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         4
          30       0.00      0.00      0.00        32
          31       0.00      0.00      0.00        20
          32       0.00      0.00      0.00        19
          33       0.00      0.00      0.00         7
          34       0.00      0.00      0.00         5
          35       0.00      0.00      0.00         5
         100       0.10      1.00      0.17        44

    accuracy                           0.10       460
   macro avg       0.00      0.03      0.00       460
weighted avg       0.01      0.10      0.02       460

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
elapsed_time_LR = time.time() - start_time_LR
print("Time taken to run Logistic Regression = ", elapsed_time_LR, "seconds")

Time taken to run Logistic Regression =  0.37736940383911133 seconds

In [ ]:
rms_LR = mean_squared_error(Y_test, y_pred_LR, squared=False)
rms_LR

80.16370478725014

#### 3.Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
start_time_DT=time.time()
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(x_train, y_train)

#Predict the response for test dataset
y_pred_DT = clf.predict(X_test)

print("Decision Tree Accuracy:",metrics.accuracy_score(Y_test, y_pred_DT))

Decision Tree Accuracy: 0.8913043478260869

In [ ]:
print(confusion_matrix(Y_test, y_pred_DT))
print(classification_report(Y_test,y_pred_DT))

[[15  0  2 ...  0  0  0]
 [ 0 24  2 ...  0  0  0]
 [ 0  1 22 ...  0  0  0]
 ...
 [ 0  0  0 ...  3  2  0]
 [ 0  0  0 ...  2  3  0]
 [ 0  0  0 ...  0  0 44]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.94        17
           1       0.96      0.92      0.94        26
           2       0.85      0.92      0.88        24
           3       0.69      0.90      0.78        10
           4       0.85      1.00      0.92        11
           5       0.87      0.93      0.90        14
           6       0.94      0.94      0.94        18
           7       0.93      0.88      0.90        16
           8       0.89      0.73      0.80        11
           9       1.00      1.00      1.00         4
          10       0.75      1.00      0.86         3
          11       1.00      0.88      0.93         8
          12       1.00      0.92      0.96        12
          13       0.64      0.78      0.70         9
          14       0.79      0.69      0.73        16
          15       0.91      0.91      0.91        11
          16       0.91      0.83      0.87        12
          17       0.75      1.00      0.86         6
          18       1.00      0.50      0.67         2
          19       1.00      1.00      1.00         4
          20       1.00      1.00      1.00         2
          21       1.00      1.00      1.00         2
          22       1.00      1.00      1.00         1
          23       1.00      1.00      1.00         4
          24       0.95      0.90      0.92        20
          25       0.94      0.97      0.95        30
          26       1.00      0.90      0.95        29
          27       1.00      1.00      1.00         1
          28       1.00      1.00      1.00         1
          29       0.80      1.00      0.89         4
          30       0.90      0.88      0.89        32
          31       0.83      0.95      0.88        20
          32       0.94      0.79      0.86        19
          33       1.00      0.43      0.60         7
          34       0.50      0.60      0.55         5
          35       0.43      0.60      0.50         5
         100       0.94      1.00      0.97        44

    accuracy                           0.89       460
   macro avg       0.89      0.88      0.88       460
weighted avg       0.90      0.89      0.89       460

In [ ]:
elapsed_time_DT = time.time() - start_time_DT
print("Time taken to run Decision Trees = ", elapsed_time_DT, "seconds")

Time taken to run Decision Trees =  0.0721278190612793 seconds

In [ ]:
rms_DT = mean_squared_error(Y_test, y_pred_DT, squared=False)
rms_DT

7.171198432376679

#### 4.SVM

In [ ]:
#Import svm model
from sklearn import svm
start_time_SVM=time.time()

#Create a svm Classifier
clf = svm.SVC()

#Train the model using the training sets
clf.fit(x_train, y_train)

#Predict the response for test dataset
y_pred_SVM = clf.predict(X_test)
print("SVM Accuracy:",metrics.accuracy_score(Y_test, y_pred_SVM))

SVM Accuracy: 0.09565217391304348

In [ ]:
print(confusion_matrix(Y_test, y_pred_SVM))
print(classification_report(Y_test,y_pred_SVM))

[[ 0  0  0 ...  0  0 17]
 [ 0  0  0 ...  0  0 26]
 [ 0  0  0 ...  0  0 24]
 ...
 [ 0  0  0 ...  0  0  5]
 [ 0  0  0 ...  0  0  5]
 [ 0  0  0 ...  0  0 44]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        17
           1       0.00      0.00      0.00        26
           2       0.00      0.00      0.00        24
           3       0.00      0.00      0.00        10
           4       0.00      0.00      0.00        11
           5       0.00      0.00      0.00        14
           6       0.00      0.00      0.00        18
           7       0.00      0.00      0.00        16
           8       0.00      0.00      0.00        11
           9       0.00      0.00      0.00         4
          10       0.00      0.00      0.00         3
          11       0.00      0.00      0.00         8
          12       0.00      0.00      0.00        12
          13       0.00      0.00      0.00         9
          14       0.00      0.00      0.00        16
          15       0.00      0.00      0.00        11
          16       0.00      0.00      0.00        12
          17       0.00      0.00      0.00         6
          18       0.00      0.00      0.00         2
          19       0.00      0.00      0.00         4
          20       0.00      0.00      0.00         2
          21       0.00      0.00      0.00         2
          22       0.00      0.00      0.00         1
          23       0.00      0.00      0.00         4
          24       0.00      0.00      0.00        20
          25       0.00      0.00      0.00        30
          26       0.00      0.00      0.00        29
          27       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         4
          30       0.00      0.00      0.00        32
          31       0.00      0.00      0.00        20
          32       0.00      0.00      0.00        19
          33       0.00      0.00      0.00         7
          34       0.00      0.00      0.00         5
          35       0.00      0.00      0.00         5
         100       0.10      1.00      0.17        44

    accuracy                           0.10       460
   macro avg       0.00      0.03      0.00       460
weighted avg       0.01      0.10      0.02       460

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
elapsed_time_SVM = time.time() - start_time_SVM
print("Time taken to run SVM = ", elapsed_time_SVM, "seconds")

Time taken to run SVM =  2.4444291591644287 seconds

In [ ]:
rms_SVM = mean_squared_error(Y_test, y_pred_SVM, squared=False)
rms_SVM

80.16370478725014

#### 5.Naive Bayes

In [ ]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Record time
start_time_NB=time.time()

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(x_train, y_train)

#Predict the response for test dataset
y_pred_NB = gnb.predict(X_test)
print("Navie Bayes Accuracy:",metrics.accuracy_score(Y_test, y_pred_NB))

Navie Bayes Accuracy: 0.14782608695652175

In [ ]:
print(confusion_matrix(Y_test, y_pred_NB))
print(classification_report(Y_test,y_pred_NB))

[[ 9  0  0 ...  0  0  0]
 [12  0  0 ...  0  0  0]
 [14  0  0 ...  0  0  0]
 ...
 [ 3  0  0 ...  0  0  0]
 [ 3  0  0 ...  0  0  0]
 [21  0  0 ...  0  0 16]]
              precision    recall  f1-score   support

           0       0.06      0.53      0.11        17
           1       0.00      0.00      0.00        26
           2       0.00      0.00      0.00        24
           3       0.00      0.00      0.00        10
           4       0.00      0.00      0.00        11
           5       0.00      0.00      0.00        14
           6       0.00      0.00      0.00        18
           7       0.00      0.00      0.00        16
           8       0.00      0.00      0.00        11
           9       0.00      0.00      0.00         4
          10       0.00      0.00      0.00         3
          11       0.00      0.00      0.00         8
          12       0.00      0.00      0.00        12
          13       0.00      0.00      0.00         9
          14       0.00      0.00      0.00        16
          15       0.00      0.00      0.00        11
          16       0.00      0.00      0.00        12
          17       0.00      0.00      0.00         6
          18       1.00      1.00      1.00         2
          19       1.00      1.00      1.00         4
          20       1.00      1.00      1.00         2
          21       1.00      1.00      1.00         2
          22       1.00      1.00      1.00         1
          23       1.00      1.00      1.00         4
          24       0.00      0.00      0.00        20
          25       0.00      0.00      0.00        30
          26       0.00      0.00      0.00        29
          27       1.00      1.00      1.00         1
          28       0.20      1.00      0.33         1
          29       0.57      1.00      0.73         4
          30       0.08      0.69      0.15        32
          31       0.00      0.00      0.00        20
          32       0.00      0.00      0.00        19
          33       0.00      0.00      0.00         7
          34       0.00      0.00      0.00         5
          35       0.00      0.00      0.00         5
         100       0.80      0.36      0.50        44

    accuracy                           0.15       460
   macro avg       0.24      0.29      0.24       460
weighted avg       0.12      0.15      0.10       460

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
elapsed_time_NB = time.time() - start_time_NB
print("Time taken to run Naive Bayes = ", elapsed_time_NB, "seconds")

Time taken to run Naive Bayes =  0.059546470642089844 seconds

In [ ]:
rms_NB = mean_squared_error(Y_test, y_pred_NB, squared=False)
rms_NB

28.76233194875608

#### 6.KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
start_time_KNN=time.time()
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred_KNN = classifier.predict(X_test)
print("KNN Accuracy:",metrics.accuracy_score(Y_test, y_pred_KNN))

KNN Accuracy: 0.9739130434782609

In [ ]:
print(confusion_matrix(Y_test, y_pred_KNN))
print(classification_report(Y_test,y_pred_KNN))

[[17  0  0 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ...  4  0  0]
 [ 0  0  0 ...  0  4  0]
 [ 0  0  0 ...  0  0 44]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        26
           2       1.00      1.00      1.00        24
           3       1.00      0.90      0.95        10
           4       1.00      1.00      1.00        11
           5       1.00      1.00      1.00        14
           6       1.00      1.00      1.00        18
           7       1.00      1.00      1.00        16
           8       0.92      1.00      0.96        11
           9       0.80      1.00      0.89         4
          10       0.67      0.67      0.67         3
          11       1.00      1.00      1.00         8
          12       0.92      1.00      0.96        12
          13       1.00      1.00      1.00         9
          14       0.88      0.88      0.88        16
          15       1.00      1.00      1.00        11
          16       1.00      1.00      1.00        12
          17       1.00      1.00      1.00         6
          18       1.00      1.00      1.00         2
          19       1.00      1.00      1.00         4
          20       1.00      1.00      1.00         2
          21       1.00      1.00      1.00         2
          22       1.00      1.00      1.00         1
          23       1.00      1.00      1.00         4
          24       0.95      1.00      0.98        20
          25       0.93      0.93      0.93        30
          26       1.00      0.97      0.98        29
          27       1.00      1.00      1.00         1
          28       1.00      1.00      1.00         1
          29       1.00      1.00      1.00         4
          30       1.00      0.94      0.97        32
          31       0.95      0.95      0.95        20
          32       0.95      1.00      0.97        19
          33       1.00      1.00      1.00         7
          34       1.00      0.80      0.89         5
          35       0.80      0.80      0.80         5
         100       1.00      1.00      1.00        44

    accuracy                           0.97       460
   macro avg       0.97      0.97      0.97       460
weighted avg       0.97      0.97      0.97       460

In [ ]:
elapsed_time_KNN = time.time() - start_time_KNN
print("Time taken to run KNN = ", elapsed_time_KNN, "seconds")

Time taken to run KNN =  0.1170799732208252 seconds

In [ ]:
rms_KNN = mean_squared_error(Y_test, y_pred_KNN, squared=False)
rms_KNN

2.751284285091474

#### 8.Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

start_time_RF=time.time()
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train, y_train)

# prediction on test set
y_pred_RF=clf.predict(X_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_test, y_pred_RF))

Accuracy: 0.8326086956521739

In [ ]:
print(confusion_matrix(Y_test, y_pred_RF))
print(classification_report(Y_test,y_pred_RF))

[[15  0  2 ...  0  0  0]
 [ 0 24  0 ...  0  0  0]
 [ 0  1 21 ...  0  0  0]
 ...
 [ 0  0  0 ...  4  0  0]
 [ 0  0  0 ...  0  5  0]
 [ 0  0  0 ...  0  0 43]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.94        17
           1       0.96      0.92      0.94        26
           2       0.91      0.88      0.89        24
           3       0.91      1.00      0.95        10
           4       0.85      1.00      0.92        11
           5       0.93      0.93      0.93        14
           6       0.84      0.89      0.86        18
           7       0.86      0.75      0.80        16
           8       0.75      0.82      0.78        11
           9       0.80      1.00      0.89         4
          10       0.75      1.00      0.86         3
          11       1.00      0.88      0.93         8
          12       1.00      0.83      0.91        12
          13       0.62      0.89      0.73         9
          14       1.00      0.69      0.81        16
          15       0.80      0.73      0.76        11
          16       0.80      0.67      0.73        12
          17       1.00      1.00      1.00         6
          18       1.00      0.50      0.67         2
          19       1.00      0.50      0.67         4
          20       0.67      1.00      0.80         2
          21       0.67      1.00      0.80         2
          22       1.00      1.00      1.00         1
          23       1.00      1.00      1.00         4
          24       0.80      0.80      0.80        20
          25       0.74      0.77      0.75        30
          26       0.69      0.76      0.72        29
          27       1.00      1.00      1.00         1
          28       1.00      1.00      1.00         1
          29       1.00      1.00      1.00         4
          30       0.85      0.72      0.78        32
          31       0.70      0.95      0.81        20
          32       0.62      0.53      0.57        19
          33       1.00      0.57      0.73         7
          34       0.57      0.80      0.67         5
          35       0.83      1.00      0.91         5
         100       0.90      0.98      0.93        44

    accuracy                           0.83       460
   macro avg       0.86      0.85      0.84       460
weighted avg       0.84      0.83      0.83       460

In [ ]:
elapsed_time_RF = time.time() - start_time_RF
print("Time taken to run Random Forest = ", elapsed_time_RF, "seconds")

Time taken to run Random Forest =  0.6490871906280518 seconds

In [ ]:
rms_RF = mean_squared_error(Y_test, y_pred_RF, squared=False)
rms_RF

9.392642819272687